In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from textwrap import wrap
from matplotlib.lines import Line2D
from matplotlib.offsetbox import OffsetImage, AnnotationBbox

In [3]:
df = pd.read_csv('./data/df_final.csv', encoding = 'cp949', low_memory = False)
df.head()

In [5]:
df_2 = df[['고장구분', '총이용시간', '총이용거리', '고장구분별_고장횟수', '날짜차이']]

In [40]:
# from category_encoders import OneHotEncoder

# encoder = OneHotEncoder(use_cat_names=True)

# encoder.fit(df_2)

# df_3 = encoder.transform(df_2)

# encoder.get_feature_names()

In [6]:
df_2.columns

Index(['고장구분', '총이용시간', '총이용거리', '고장구분별_고장횟수', '날짜차이'], dtype='object')

In [7]:
df_2['고장구분'].unique()

array(['단말기', '타이어 ', '체인', '기타 ', '안장', '페달'], dtype=object)

In [113]:
df_3 = df_2[df_2['고장구분']=='체인']
df_3.drop(columns=['고장구분'], inplace=True)

features = df_3[['총이용시간', '총이용거리', '고장구분별_고장횟수']]
label = df_3['날짜차이']

In [46]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, label)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
model = LogisticRegression(max_iter=1000)
model.fit(train_features, train_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
print(model.score(train_features, train_labels))
print(model.score(test_features, test_labels))
print(model.coef_)

0.1145933014354067
0.09684361549497848
[[-8.58301874e+00 -8.13069128e+00  9.88155807e-01]
 [-6.38430882e+00 -4.99688649e+00  1.00446990e+00]
 [-4.51178274e+00 -4.10521759e+00  9.60080723e-01]
 [-3.51132306e+00 -2.91793152e+00  9.87302236e-01]
 [-3.13929640e+00 -2.27813293e+00  8.92477580e-01]
 [-2.42239844e+00 -1.97893462e+00  8.45829844e-01]
 [-2.18278692e+00 -1.63632626e+00  1.05328419e+00]
 [-1.92559758e+00 -8.01259052e-01  9.34436379e-01]
 [-1.69991375e+00 -1.08310480e+00  5.63888597e-01]
 [-1.33985480e+00 -1.47497814e+00  8.90534499e-01]
 [-1.64118368e+00 -7.64840265e-01  7.64714901e-01]
 [-9.45412492e-01 -1.34563618e+00  8.80533266e-01]
 [-1.11491052e+00 -5.84589787e-01  7.45418182e-01]
 [-2.42757859e-01 -1.11910773e+00  8.97362416e-01]
 [-6.88626680e-01 -9.35875546e-01  8.86386243e-01]
 [-6.42276025e-01 -3.25876016e-01  6.90964043e-01]
 [-9.28748845e-01 -3.47942570e-01  7.47981596e-01]
 [-4.45522136e-01 -5.30287143e-01  6.04369418e-01]
 [-4.59558777e-01 -4.08944953e-01  7.268557

## 파이캐럿

In [14]:
import pycaret

In [15]:
from pycaret.classification import *

In [99]:
# Importing module and initializing setup 
from pycaret.regression import * 
data = df_3
s = setup(data, numeric_features=['고장구분별_고장횟수'], target = '날짜차이', fold_shuffle=True)

AttributeError: 'Simple_Imputer' object has no attribute 'fill_value_categorical'

In [100]:
best = compare_models()

In [106]:
from sklearn.linear_model import HuberRegressor

from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, label)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

model = HuberRegressor()
model.fit(train_features, train_labels)

print(model.score(train_features, train_labels))
print(model.score(test_features, test_labels)) 

0.23337673938012726
0.327065294477877


In [114]:
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, label)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

model = GradientBoostingRegressor()
model.fit(train_features, train_labels)

print(model.score(train_features, train_labels))
print(model.score(test_features, test_labels)) 

0.512214582265118
0.29857811877250096
